### ISSUE TITLE
Example form usage

### ISSUE THREAD

**Issue by KirbyFox** [Sylius/SyliusElasticSearchPlugin#24]
Please could you provide sample code to demonstrate how to embed the search form/textbox within a view?

**Comment by Arminek** [comment]
Hey take a look at http://docs.ongr.io/FilterManagerBundle/examples/custom_controller

**Comment by KirbyFox** [comment]
Thanks @Arminek - Also https://stackoverflow.com/a/45080984/8214497

**Comment by Arminek** [comment]
Nice :wink:
