### ISSUE TITLE
limit value in configuration is not respected in pager.php

### ISSUE THREAD

**Issue by gomcodoctor** [Sylius/SyliusElasticSearchPlugin#68]
Hello,

SyliusElasticSearchPlugin/src/Filter/Widget/Pager.php

line number 43 should be changed 

from

        $state->addOption('limit', (int) $request->get('limit', 10));

to

        $state->addOption('limit', $request->get('limit', $this->getOption('limit', 10)));

Otherwise search page always show 10 results

**Comment by psihius** [comment]
I fixed this in my PR, @pamil please close :)

**Comment by pamil** [comment]
That's true! 👍
