### ISSUE TITLE
The current implementation does not support updating Elasticsearch when an entity is updated.

### ISSUE THREAD

**Issue by keevitaja** [Sylius/SyliusElasticSearchPlugin#76]
Title comes from readme...

How to solve this issue for the non-technical staff who manages the shop products?

Impossible to ask them to use ssh and run cli command. cron is not an option unless i run it way too often.

100k+ products and stock changes frequently via api.

**Comment by pamil** [comment]
In fact it just have been implemented in `master` branch, but it isn't included in any release as additional maintenance is needed before that (more tests & cleaning up the codebase). That being said, if you feel comfortable with relying on development branch, you can try running it and see if the current implementation is satisfactory :)

**Comment by psihius** [comment]
This has been pushed to the latest tag "1.0.0-beta.17", closing
