### ISSUE TITLE
Missing product updates because of bulk size in Commands

### ISSUE THREAD

**Issue by 11mb** [Sylius/SyliusElasticSearchPlugin#81]
When the updateProductIndexCommand loops through the productDocuments, every 100th time the elasticsearchManager:commit method will be triggered. When the size of productDocuments is not exact  divisible by 100 there are documents left that are not committed

**Comment by JanTvrdik** [comment]
https://github.com/Sylius/SyliusElasticSearchPlugin/pull/78

**Comment by 11mb** [comment]
Ok second time :), guess I don't use the right search terms "is:issue is:open "

**Comment by psihius** [comment]
This has been refactored and is fixed in newer tags
