### ISSUE TITLE
Customizing documents

### ISSUE THREAD

**Issue by bitbager** [Sylius/SyliusElasticSearchPlugin#86]
Is there any recommended way of customizing documents, for example by extending them from the vendor?

**Comment by pamil** [comment]
Basically it's possible by extending documents, views & their factories by 3rd party applications. You can take a look at https://github.com/URBANARA/UrbanaraCatalogPromotionPlugin/tree/master/src/ElasticSearch to get the overall idea.

**Comment by psihius** [comment]
Documents are basically DTO's with setters and getters, just extend the base once.
